name: Build Snap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: specc-snap
          path: ${{ steps.snapcraft.outputs.snap }}